// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniBookstore.Mvc.Data;

#nullable disable

namespace MiniBookstore.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613045202_AddBookCode")]
    partial class AddBookCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCode = "BK001",
                            GenreId = 1,
                            Isbn = "ISBN-978-01",
                            Price = 150000m,
                            Publisher = "NXB Trẻ",
                            StockQuantity = 25,
                            Title = "C# Programming Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            BookCode = "BK002",
                            GenreId = 2,
                            Isbn = "ISBN-978-02",
                            Price = 95000m,
                            Publisher = "NXB Tổng Hợp",
                            StockQuantity = 5,
                            Title = "Đắc Nhân Tâm"
                        },
                        new
                        {
                            Id = 3,
                            BookCode = "BK003",
                            GenreId = 1,
                            Isbn = "ISBN-978-03",
                            Price = 450000m,
                            Publisher = "Prentice Hall",
                            StockQuantity = 3,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 4,
                            BookCode = "BK004",
                            GenreId = 3,
                            Isbn = "ISBN-978-04",
                            Price = 200000m,
                            Publisher = "NXB Tri Thức",
                            StockQuantity = 15,
                            Title = "Sapiens - Lược Sử Loài Người"
                        },
                        new
                        {
                            Id = 5,
                            BookCode = "BK005",
                            GenreId = 1,
                            Isbn = "ISBN-978-05",
                            Price = 520000m,
                            Publisher = "O'Reilly Media",
                            StockQuantity = 3,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 6,
                            BookCode = "BK006",
                            GenreId = 4,
                            Isbn = "ISBN-978-06",
                            Price = 75000m,
                            Publisher = "NXB Văn Học",
                            StockQuantity = 30,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            Id = 7,
                            BookCode = "BK007",
                            GenreId = 1,
                            Isbn = "ISBN-978-07",
                            Price = 680000m,
                            Publisher = "Manning Publications",
                            StockQuantity = 8,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 8,
                            BookCode = "BK008",
                            GenreId = 2,
                            Isbn = "ISBN-978-08",
                            Price = 85000m,
                            Publisher = "NXB Hội Nhà Văn",
                            StockQuantity = 2,
                            Title = "Tuổi Trẻ Đáng Giá Bao Nhiêu"
                        });
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Văn học"
                        });
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Book", b =>
                {
                    b.HasOne("MiniBookstore.Mvc.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.SaleItem", b =>
                {
                    b.HasOne("MiniBookstore.Mvc.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniBookstore.Mvc.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("MiniBookstore.Mvc.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
